task :default => 'morning:get_ready'

namespace :morning do
  desc "Silence the alarm"
  task :turn_off_alarm do
    puts "Turned off the goddamn alarm."
  end

  desc "Make me a fancy man"
  task :groom_self do
    puts "Brush teeth."
    puts "Vodka mouthwash."
    puts "Comb beard."
  end

  desc "Recaffeinate"
  task :make_coffee do
    cups = ENV['COFFEE_CUPS'] || 2
    puts "Make #{ cups } cups of coffee."
  end

  desc "God I hate that horrible little dog"
  task :walk_dog do
    puts "Walk horrible little dog."
  end

  desc "Peform all tasks for human decency"
  task :get_ready => [:turn_off_alarm, :groom_self, :make_coffee, :walk_dog] do
    puts "All ready."
  end

end

namespace :morning do
  task :groom_self do
    puts "Shave shoulders."
  end
end

namespace :afternoon do
  desc "Make special afternoon coffee."
  task :make_coffee do
    Rake::Task['morning:make_coffee'].invoke
    puts "Added rum."
    puts "Ready for the afternoon."
  end
end














