# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35faa41131767c14f20f3abd317397a16add122e53154d3b99471c3d8daec25aa21dbc9c42a0d5744c80de6da07c7de89c554e277d0a1c2711974ac4ed5e5bf0

test:
  secret_key_base: adbc188ea9611de1f49eaddf994b2aca39492626457db00be82ae41b516b0e877a48cab3e95e58c4d1bbb0b83129dc29490c571f8185752d6ecda903f6ab519c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
