# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60541d304514b1600dc24d1db5af07ee55934bf4f3ce7f9a7eab4886c010c5c5d09e38066b8641b4e8f9799496f1f4de4ac45abd1077d2b2262664d107088141

test:
  secret_key_base: 9d89860b715596626abac00072d1717200b065ecd9c7bae5ab18531d85c1059ddd40411d332f5970791fab5753292a4b2642e011c874fa7900c455d1089119e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: '888'
  secret_token: '555'
